---
title: "Arbeidskrav4"
format: html
editor: visual
---

## Study design

Temaet jeg har valgt å ta for meg er intervalltrenings påvirkning på det maksimale oksygenopptaket (VO~2maks~). VO~2maks~  kan defineres som kroppens maksimale evne til å ta opp og omsette oksygen, altså den maksimale hastigheten på den aerobe energiomsetningen.

Fick´s ligning illustrerer de bestemmende faktorene for VO~2maks,~ som er minuttvolum (MV), arteriell oksygen og venøs oksygen.

VO~2maks~ har en sterk assosiasjon til prestasjon og toppidrett, men sees også på som en sterk indikator for generell helse. Kunnskap knyttet til dette temaet omhandler derfor ikke kun prestasjon innen toppidretten, men også den generelle helsen i befolkningen. En lav VO~2maks~ sees på som en sterk prediktor for tidlig død (Lee et al., 2010; Sparks et al., 2024; Basset & Howley, 1997; Kodama et al. 2009).

Intervalltrening er en effektiv og tidsbesparende måte å øke sin VO~2maks~ på, og kan derfor være enklere og smartere å prioritere for de som ønsker en bedre utholdenhet og sterkere helse. Det er nyttig å vite hvilken intervalltrening som er mest effektiv, enten det er kortere intervalldrag, eller lengre. Det er dette jeg skal undersøke i denne oppgaven.

Forskerne i studiene jeg har valgt ut prøver alle å finne ut hvilken intervallform som best øker VO~2maks~ og utholdenhetsprestasjonen. Studiene har noe ulik tilnærming til temaet, og ulike hypoteser og problemstillinger. Duffield et al. (2006) undersøkte hvordan høyintensiv intervalltrening (HIT) påvirket VO~2maks~ under kraftig, konstant belastning. Montero et al. (2015) testet hypotesen om at økningen i VO~2maks~ etter 6 uker med moderat utholdenhetstrening skyldtes hematologiske tilpasninger, ikke muskeltilpasninger. Sindiani et al. (2017) sammenliknet effekten av to ulike intervalltreningsprogrammer. Formålet var å finne ut om rekkefølgen på intervallene, til tross for totalt likt arbeid, ville gi ulike fysiologiske effekter. Helgerud et al. (2007) sammenliknet effekten av utholdenhetstrening med ulik intensitet og metode, men med likt totalt arbeid. Hypotesen deres var at trening ved lav intensitet (LIT) og moderat intensitet (MIT) ville gi mindre effekt på VO~2maks~ enn HIT. Rønnestad et al. (2020) sammenliknet effektene av en ukes HIT-mikrosyklus med enten korte eller lange intervalldrag. Hypotesen deres var at korte intervaller ville gi bedre effekt på utholdenhetsprestasjon enn lange intervaller.Denne studien sammenlignet effekten av en ukes HIT-mikrosyklus med enten korte eller lange intervaller. Hypotesen var at korte intervaller ville gi bedre forbedringer i indikatorer på utholdenhetsprestasjon enn lange intervaller.

Likt for alle studiene er at de har en hypotese om at HIT trening gir bedre fysiologiske tilpasninger enn trening med lavere intensitet, da kortere intervaller ofte vil gi et høyere treningsindusert stress og større fysiologiske adapsjoner.

Alle de fem studiene er intervensjonsstudier som undersøker effekten av ulik intensitet på intervalltreningen på VO~2maks~. Studiene til Duffield et al. (2006) og Rønnestad et al. (2020) har benyttet seg av et crossover-design, mens de andre benyttet seg av et randomisert kontrollstudie-design.

Utvalgsstørrelse i studiene varierer stort, fra 10 til 55 deltakere, og det er lite informasjon å oppdrive om hvordan de innhentet deltakere til studiene sine. Ingen av studiene opplyser om de har gjort statistiske analyser for å bestemme nødvendig utvalgsstørrelse. Dette er en viktig begrensning, fordi små utvalg ofte kan føre til lav statistisk styrke og gir økt risiko for type II feil. Både lite informasjon om rekruttering og hvordan de beregnet utvalgsstørrelse er svakheter i studiene. Sannsynligvis er det blitt gjort, men det er ikke opplyst om i artiklene. Det gjør at en kan stille spørsmålstegn om hvorvidt dataene deres er generaliserbare for en større del av populasjonen. Når en studie har et lite eller ikke-representativt utvalg, kan det være utfordrende å overføre resultatene til den større befolkningen. For eksempel, hvis deltakerne er valgt på en måte som ikke reflekterer eller representerer den totale populasjonen (som f.eks idrettsstudenter i forskningsprosjekter på trening), kan resultsatene være ikke-representative for befolkningen ellers med et lavere fysisk nivå eller utgangspunkt. Det er viktig med informasjon om hvordan deltakerne ble rekruttert for å vite om utvalget er representativt for den gruppen man ønsker å generalisere til.

En utilstrekkelig beregnet utvalgsstørrelse kan føre til at studien mangler statistisk styrke, som er evnen til å oppdage en faktisk effekt hvis den eksisterer. Uten en presis beregning av nødvendig utvalgsstørrelse risikerer man å ha for få deltakere til å oppdage små og betydningsfulle effekter, og øker igjen risikoen for type II feil.

Samlet sett er informasjon om rekruttering og beregning av utvalgsstørrelse avgjørende for å vurdere studienes vitenskapelige styrke, troverdighet og hvorvidt resultatene kan overføres til en bredere befolkning.

Rønnestad og kolleger skriver at 18 mannlige deltakere på nasjonalt nivå enten i terrengsykling eller landeveissykling meldte seg frivillig til å delta i studiet. Duffield og kolleger opplyser kun om at de rekrutterte 10 aktive og friske kvinner frivillig. Montero og kolleger opplyser om at de rekrutterte 16 utrente, men friske menn til studien sin. Sindiani og kolleger beskriver at de rekrutterte 40 friske, unge menn i alderen 22-25 som var idrettsstudenter. Helgerud og kolleger har også rekruttert 45 mannlige studenter, som alle var aktive i idrett fra før av.

Studiene er designet på ulike måter, og varierer i lengde på 3 til 8 uker. Samtlige studier er lagt opp med en testperiode før treningsintervensjonen, og en testperiode etter treningsintervensjonen. Testene ble gjennomført pre- og post-intervensjon, deriblant VO~2maks~-test, laktatprofil, arbeidsøkonomi, flebotomi, hemoglobinmasse og konsentrasjon, m.m. VO2maks er den mest relevante variabelen å se på i henhold til mitt tema, og responsen en får på ulike typer intervalltrening. Alle de andre variablene som er målt er høyst aktuelle og knytter seg sterkt opp til VO~2maks~ responsen. Parede og u-parede t-tester og ANOVA er den vanligste statistiske analysen og ble brukt i samtlige studier for å sammenlikne effekten mellom grupper. Det ble også brukt Cohen´s d for å finne effektstørrelse, som brukes for å beskrive størrelsen på en forskjell mellom to grupper, uavhengig av utvalgsstørrelse. Effektstørrelsen gir en indikasjon på hvor stor eller liten en effekt er, og brukes for å vurdere betydningen av forskningsfunn i tillegg til statistisk signifikans.

Samtlige studier konkluderte med at trening med høyere intensitet er bedre for å øke VO~2maks~ enn trening med lavere intensitet eller kontinuerlig arbeid. Det er brukt både parede og uavhengige t-tester for å sammenlikne forskjeller mellom to grupper, og ANOVA for å studere forskjellene mellom tre eller flere grupper, for å finne ut om det er en signifikant forskjell mellom de, og om det er statistisk betydningsfult. Dette er gjort i tråd med oppbygningen av studiedesignene i disse studiene.

Helgerud et al. (2007) sammenliknet effektene av 4 ulike intervaller sin påvirkning på VO2maks, og fant at 4x4 min intervaller og 15x15 sekund økte VO~2maks~ signifikant i forhold til gruppen som hadde lav intensitet eller trente på laktatterskel med henholdsvis 7,3% og 5,5%. Rønnestad et al. (2020) fant data som støttet hypotesen deres om at kortere intervaller gir bedre adaptasjoner til utholdenhet og prestasjon enn lengre intervaller. Dog økte begge gruppene i VO~2maks~, men gruppen med kortere intervaller økte mest innad i gruppen. De resterende studiene er enig i at intervaller gjennomført på en høy intensitet gir bedre utholdenhetsadapsjoner enn LIT eller kontinuerlig arbeid, for å forbedre VO~2maks~ hos både moderat godt trente og toppidrettsutøvere.

Referanser:

Bassett, D. R., Jr, & Howley, E. T. (1997). Maximal oxygen uptake: "classical" versus "contemporary" viewpoints. *Medicine and science in sports and exercise*, *29*(5), 591–603. https://doi.org/10.1097/00005768-199705000-00002

Duffield, R., Edge, J., & Bishop, D. (2006). Effects of high-intensity interval training on the VO2 response during severe exercise. *Journal of science and medicine in sport*, *9*(3), 249–255. <https://doi.org/10.1016/j.jsams.2006.03.014>

Helgerud, J., Høydal, K., Wang, E., Karlsen, T., Berg, P., Bjerkaas, M., Simonsen, T., Helgesen, C., Hjorth, N., Bach, R., & Hoff, J. (2007). Aerobic high-intensity intervals improve VO2max more than moderate training. *Medicine and science in sports and exercise*, *39*(4), 665–671. <https://doi.org/10.1249/mss.0b013e3180304570>

Kodama, S., Saito, K., Tanaka, S., Maki, M., Yachi, Y., Asumi, M., Sugawara, A., Totsuka, K., Shimano, H., Ohashi, Y., Yamada, N., & Sone, H. (2009). Cardiorespiratory fitness as a quantitative predictor of all-cause mortality and cardiovascular events in healthy men and women: a meta-analysis. *JAMA*, *301*(19), 2024–2035. https://doi.org/10.1001/jama.2009.681

Lee, D. C., Artero, E. G., Sui, X., & Blair, S. N. (2010). Mortality trends in the general population: the importance of cardiorespiratory fitness. *Journal of psychopharmacology (Oxford, England)*, *24*(4 Suppl), 27–35. https://doi.org/10.1177/1359786810382057

Montero, D., Cathomen, A., Jacobs, R.A., Flück, D., de Leur, J., Keiser, S., Bonne, T., Kirk, N., Lundby, A.-K. and Lundby, C. (2015), Haematological rather than skeletal muscle adaptations contribute to the increase in peak oxygen uptake induced by moderate endurance training. J Physiol, 593: 4677-4688. <https://doi.org/10.1113/JP270250>

Sindiani, M., Eliakim, A., Segev, D., & Meckel, Y. (2017). The effect of two different interval-training programmes on physiological and performance indices. *European journal of sport science*, *17*(7), 830–837. <https://doi.org/10.1080/17461391.2017.1321687>

Sparks, J. R., Wang, X., Lavie, C. J., Zhang, J., & Sui, X. (2024). Cardiorespiratory Fitness as a Predictor of Non-Cardiovascular Disease and Non-Cancer Mortality in Men. *Mayo Clinic proceedings*, *99*(8), 1261–1270. https://doi.org/10.1016/j.mayocp.2023.11.024

Rønnestad, B. R., Hansen, J., Nygaard, H., & Lundby, C. (2020). Superior performance improvements in elite cyclists following short-interval vs effort-matched long-interval training. *Scandinavian journal of medicine & science in sports*, *30*(5), 849–857. https://doi.org/10.1111/sms.13627
